# -*- coding: utf-8 -*-
"""API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hvLzO5cjoKS3p_PueLxc-jni3ddwCxc
"""

import requests

url = "https://api.clickup.com/api/v2/list/901202319556/task?subtasks=true"
headers = {
    "Authorization": "pk_50684561_EGE0I4TLGHZF3KL77LNPEVRXWXCTKYTH"
}

# Define params as an empty dictionary (or with desired parameters)
params = {}

r = requests.get(url, headers=headers, params=params)
print(r.status_code)
print(r.json())

import pandas as pd
sample_dict_json = {'id': 1, 'name': 'Item A', 'value': 100}
df_from_dict = pd.DataFrame([sample_dict_json])
print("DataFrame from a dictionary:")
print(df_from_dict)
print("\n")

sample_list_json = [
    {'id': 1, 'name': 'Task 1', 'status': 'open'},
    {'id': 2, 'name': 'Task 2', 'status': 'closed'},
    {'id': 3, 'name': 'Task 3', 'status': 'open'}
]
df_from_list = pd.DataFrame(sample_list_json)
print("DataFrame from a list of dictionaries:")
print(df_from_list)
print("\n")


try:
    api_json_data = r.json()
    if isinstance(api_json_data, list):
        df_api = pd.DataFrame(api_json_data)
        print("DataFrame from API list response:")
        print(df_api)
    elif isinstance(api_json_data, dict):
        df_api = pd.DataFrame([api_json_data])
        print("DataFrame from API dictionary response:")
        print(df_api)
    else:
        print("API response is not a recognized JSON format (list or dict) for DataFrame conversion.")
except NameError:
    print("Error: 'r' (the response object from the API call) is not defined in this scope. Please ensure the API call in the previous cell has been executed successfully and 'r' is available, or re-run it.")
except Exception as e:
    print(f"An error occurred during API JSON processing: {e}")