# -*- coding: utf-8 -*-
"""certification_testdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0b04KtR_zvhNi9elDUz4rP5kWN1JO-x
"""

from __future__ import annotations
import os
from pathlib import Path
from typing import Any
import numpy as np
import pandas as pd
import requests
from IPython.display import display

"""## 1) Configuration"""

import requests

url = "https://api.clickup.com/api/v2/list/901202319556/task?subtasks=true"
headers = {
    "Authorization": "pk_93882701_5X39IECQRBNWFTVZBYSJH5CXKU79HS55"
}

r = requests.get(url, headers=headers)
print(r.status_code)
print(r.json())

api_json_data = r.json()
df_api = pd.json_normalize(api_json_data['tasks'])
df_api.head(3)

df_api.info()

df_api["status.status"].unique()

import pandas as pd

# Process 'assignees', 'watchers', 'tags' and 'custom_fields' (lists of dicts)
# For 'assignees' and 'watchers', extract usernames
df_api['assignee_names'] = df_api['assignees'].apply(lambda x: [d['username'] for d in x] if isinstance(x, list) else [])
df_api['watcher_names'] = df_api['watchers'].apply(lambda x: [d['username'] for d in x] if isinstance(x, list) else [])

# For 'tags', extract tag names
df_api['tag_names'] = df_api['tags'].apply(lambda x: [d['name'] for d in x] if isinstance(x, list) else [])

# For 'custom_fields', extract 'name' and 'value' where applicable. This can be complex.
# Let's create a dictionary of custom field names and their values
def process_custom_fields(fields_list):
    if not isinstance(fields_list, list):
        return {}
    field_data = {}
    for field in fields_list:
        field_name = field.get('name')
        field_value = field.get('value')
        if field_name:
            if isinstance(field_value, dict) and 'percent_completed' in field_value:
                field_data[f'custom_field_{field_name}_percent_completed'] = field_value.get('percent_completed')
            elif isinstance(field_value, dict) and 'type' in field_value:
                field_data[f'custom_field_{field_name}_type'] = field_value.get('type')
            else:
                field_data[f'custom_field_{field_name}'] = field_value
    return field_data

custom_fields_df = df_api['custom_fields'].apply(process_custom_fields).apply(pd.Series)
df_api = pd.concat([df_api, custom_fields_df], axis=1)

# Drop original nested columns now that their data is extracted/flattened
df_flattened = df_api.drop(columns=[
    'assignees', 'watchers', 'checklists', 'tags', 'custom_fields',
    'group_assignees', 'dependencies', 'linked_tasks', 'locations'
])

# Display the first few rows and the info of the new flattened DataFrame
print("\nFlattened DataFrame head:")
print(df_flattened.head(2))
print("\nFlattened DataFrame info:")
df_flattened.head(2)

(df_flattened.columns)

"""## 2) Load local reference data extracted from the Alteryx workflow"""

data = {
    'Name': [
        'Jenny Wrench',
        'Lynn Carelse',
        'Carl Brink'
    ]
}
resigned_names = pd.DataFrame(data)
glossary = df_flattened

display(glossary.head(2))
display(resigned_names)

"""## 3) Helper functions"""

from typing import Any

def epoch_ms_to_datetime(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, unit="ms", errors="coerce")

def epoch_ms_to_date(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, unit="ms", errors="coerce").dt.normalize()

def clean_text_columns(df: pd.DataFrame) -> pd.DataFrame:
    text_cols = df.select_dtypes(include=["object", "string"]).columns
    for col in text_cols:
        df[col] = (
            df[col]
            .fillna("")
            .astype(str)
            .str.strip()
        )
    return df

def first_or_none(value: Any) -> Any:
    if isinstance(value, list) and value:
        return value[0]
    return None

def fetch_clickup_tasks(api_token: str, base_url: str, params: dict[str, str]) -> list[dict[str, Any]]:
    if not api_token or api_token == "PASTE_YOUR_CLICKUP_API_TOKEN_HERE":
        raise ValueError("Set CLICKUP_API_TOKEN before running the notebook.")

    headers = {
        "Authorization": api_token
    }

    response = requests.get(base_url, headers=headers, params=params, timeout=60)
    response.raise_for_status()
    payload = response.json() # Corrected: use .json() to parse the response body
    return payload.get("tasks", []) # Corrected: get 'tasks' from the parsed JSON payload

def extract_custom_field_value(task: dict[str, Any], field_index: int = 1) -> Any:
    custom_fields = task.get("custom_fields", []) or []
    if len(custom_fields) > field_index:
        return custom_fields[field_index].get("value")
    return None

def normalize_tasks(tasks: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for task in tasks:
        assignees = task.get("assignees", []) or []
        tags = task.get("tags", []) or []

        row = {
            "Name": first_or_none(assignees).get("username") if first_or_none(assignees) else None,
            "Expire Date": extract_custom_field_value(task, 1),
            "date_created": task.get("date_created"),
            "Update Date": task.get("date_updated"),
            "due_date": task.get("due_date"),
            "Certification Name": task.get("name"),
            "CU Status": (task.get("status") or {}).get("status"),
            "Tag": first_or_none(tags).get("name") if first_or_none(tags) else None,
        }
        rows.append(row)

    df = pd.DataFrame(rows)
    return df

def apply_employment_status(df: pd.DataFrame, resigned_df: pd.DataFrame) -> pd.DataFrame:
    resigned_set = set(resigned_df["Name"].dropna().astype(str).str.strip())
    df["Employment Status"] = np.where(
        df["Name"].fillna("").astype(str).str.strip().isin(resigned_set),
        "Resigned",
        "Active"
    )
    return df

def build_completed_branch(df: pd.DataFrame) -> pd.DataFrame:
    completed = df.copy()
    completed = completed[(completed["Name"].notna()) | (completed["due_date"].notna())]
    completed = completed[completed["CU Status"].eq("Done")]
    completed = completed[completed["Tag"].eq("cert")]

    completed["Record Date"] = completed["date_created"].dt.normalize()
    completed["Last Updated"] = completed["Update Date"].dt.normalize()
    completed["Expiration Date"] = np.where(
        completed["Expire Date"].isna(),
        (pd.Timestamp.today().normalize() + pd.DateOffset(years=10)),
        completed["Expire Date"]
    )
    # Corrected this line to use .dt.normalize() and errors='coerce'
    completed["Expiration Date"] = pd.to_datetime(completed["Expiration Date"], errors='coerce').dt.normalize()
    completed["Status"] = np.where(
        pd.Timestamp.today().normalize() > completed["Expiration Date"],
        "Expired",
        "Active"
    )
    completed["Latest Flag"] = "1"

    # recreate Alteryx summarize + join logic
    max_record = (
        completed.groupby(["Name", "Certification Name"], dropna=False)["Record Date"]
        .max()
        .rename("Max_Record Date")
        .reset_index()
    )
    completed = completed.merge(max_record, on=["Name", "Certification Name"], how="left")
    completed["Latest Flag"] = np.where(
        completed["Record Date"].eq(completed["Max_Record Date"]),
        "1",
        "0"
    )
    completed = completed.drop(columns=["Max_Record Date"])

    keep_cols = [
        "Name", "Record Date", "Last Updated", "Latest Flag",
        "Certification Name", "Expiration Date", "Status", "Employment Status"
    ]
    return completed[keep_cols].copy()

def build_planned_branch(df: pd.DataFrame) -> pd.DataFrame:
    planned = df.copy()
    planned = planned[(planned["Name"].notna()) | (planned["due_date"].notna())]
    planned = planned[planned["CU Status"].ne("Done")]
    planned = planned[planned["Tag"].eq("cert")]

    planned["Planned Exam Date"] = planned["due_date"]
    planned["Record Date"] = planned["date_created"].dt.normalize()
    planned["Last Updated"] = planned["Update Date"].dt.normalize()
    planned["Status"] = "Planned"
    planned["Latest Flag"] = "1"

    keep_cols = [
        "Name", "Record Date", "Last Updated", "Latest Flag",
        "Certification Name", "Planned Exam Date", "Status", "Employment Status"
    ]
    return planned[keep_cols].copy()

def standardise_certification_fields(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["Certification Name"] = df["Certification Name"].replace({
        "Tableau Desktop Specialist (no expiry date)": "Tableau Desktop Specialist",
        "DESIGN KIT: HUMAN-CENTERED DESIGN": "Design Kit: Human-Centered Design",
        "DESIGN KIT: PROTOTYPING": "Design Kit: Prototyping",
        "AWS Certified Cloud Practitioner": "AWS Cloud Practitioner",
    })

    df.loc[df["Certification Name"].fillna("").str.contains("SnowPro Core", case=False, na=False), "Certification Name"] = "SnowPro Core"

    cert_name = df["Certification Name"].fillna("")

    df["Technology"] = np.select(
        [
            cert_name.str.contains("Tableau", case=False, na=False),
            cert_name.str.contains("Alteryx", case=False, na=False),
            cert_name.str.contains("Google", case=False, na=False),
            cert_name.str.contains("AWS", case=False, na=False),
            cert_name.str.contains("Snowflake", case=False, na=False),
            cert_name.str.contains("SnowPro", case=False, na=False),
            cert_name.str.contains("wherescape", case=False, na=False),
            cert_name.str.contains("Trifacta", case=False, na=False),
            cert_name.str.contains("Data Vault", case=False, na=False),
            cert_name.str.contains("Design Kit", case=False, na=False),
            cert_name.str.contains("Salesforce", case=False, na=False),
            cert_name.str.contains("Matillion", case=False, na=False),
        ],
        [
            "Salesforce",
            "Alteryx",
            "Google",
            "AWS",
            "Snowflake",
            "Snowflake",
            "Wherescape",
            "Alteryx",
            "Data Vault",
            "Design Kit",
            "Salesforce",
            "Matillion",
        ],
        default="Other"
    )

    name_col = df["Name"].fillna("")
    df.loc[name_col.str.contains("Thembani", case=False, na=False), "Name"] = "Thembani Faleni"
    df.loc[name_col.str.contains("Flora", case=False, na=False), "Name"] = "Flora Kundaeli"

    return df

def prepare_glossary(glossary_df: pd.DataFrame) -> pd.DataFrame:
    glossary_df = glossary_df.copy()

    glossary_df["Cost"] = glossary_df["Cost"].fillna("").astype(str).str.replace("$", "", regex=False)
    glossary_df["Currency"] = "USD"
    glossary_df["Cost"] = np.where(
        glossary_df["Cost"].isin(["Free", ""]),
        "0",
        glossary_df["Cost"]
    )
    glossary_df["Partner"] = pd.to_numeric(glossary_df["Partner"], errors="coerce").fillna(0).astype(int)
    glossary_df["Cost"] = pd.to_numeric(glossary_df["Cost"], errors="coerce").fillna(0.0)
    glossary_df["Validity (Years)"] = pd.to_numeric(glossary_df["Validity (Years)"], errors="coerce")

    keep = ["Certification Name", "Technology", "Prerequisites", "Cost", "Currency", "Validity (Years)", "Partner"]
    return glossary_df[keep].copy()

def build_date_spine(start_date: pd.Timestamp, end_date: pd.Timestamp) -> pd.DataFrame:
    return pd.DataFrame({"Date": pd.date_range(start=start_date, end=end_date, freq="D")})

def expand_by_date(base_df: pd.DataFrame, date_df: pd.DataFrame) -> pd.DataFrame:
    base_df = base_df.copy()
    date_df = date_df.copy()
    base_df["__key"] = 1
    date_df["__key"] = 1
    out = base_df.merge(date_df, on="__key", how="outer").drop(columns="__key")
    return out

def recompute_status_over_time(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    df["Status"] = np.select(
        [
            (df["Expiration Date"] > df["Date"]) & (df["Planned Exam Date"].isna()),
            (df["Expiration Date"] <= df["Date"]) & (df["Planned Exam Date"].isna()),
            (df["Planned Exam Date"].notna()) & (df["Planned Exam Date"] > df["Date"]),
            (df["Planned Exam Date"].notna()) & (df["Planned Exam Date"] <= df["Date"]),
        ],
        [
            "Active",
            "Expired",
            "Planned",
            "Planned - Past Exam Date",
        ],
        default=df["Status"]
    )

    df["Status"] = np.where(
        (df["Status"] == "Planned") & (df["Planned Exam Date"].isna()),
        "Planned - No Exam Date",
        df["Status"]
    )

    df["Expiration Date"] = np.where(
        df["Status"].astype(str).str.contains("Planned", na=False),
        df["Planned Exam Date"] + pd.to_timedelta((df["Validity (Years)"].fillna(0) * 365.25), unit="D"),
        df["Expiration Date"]
    )
    df["Expiration Date"] = pd.to_datetime(df["Expiration Date"], errors="coerce").dt.normalize()

    df["Expiration Date Indicator"] = np.where(
        df["Status"].astype(str).str.contains("Planned", na=False),
        "Projected",
        "Actual"
    )
    df["Expiration Date Indicator"] = np.where(
        df["Expiration Date"].isna(),
        pd.NA,
        df["Expiration Date Indicator"]
    )

    df["Status"] = np.where(
        df["Status"].astype(str).str.contains("Planned", na=False) & (df["Date"] >= df["Planned Exam Date"]),
        "Projected Active",
        df["Status"]
    )
    df["Status"] = np.where(
        (df["Status"] == "Projected Active") & (df["Date"] >= df["Expiration Date"]),
        "Projected Expired",
        df["Status"]
    )

    return df

def finalise_output(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    out["Cost ($"] = out["Cost"]
    keep = [
        "Date",
        "Name",
        "Certification Name",
        "Technology",
        "Status",
        "Expiration Date",
        "Expiration Date Indicator",
        "Planned Exam Date",
        "Validity (Years)",
        "Cost ($",
        "Record Date",
        "Last Updated",
        "Latest Flag",
        "Employment Status",
        "Partner",
    ]
    existing_keep = [c for c in keep if c in out.columns]
    out = out[existing_keep].copy()

    out = out.sort_values(
        by=["Date", "Name", "Status", "Expiration Date", "Planned Exam Date"],
        ascending=[True, True, True, True, True],
        na_position="last"
    ).reset_index(drop=True)

    return out

"""## 4) Run the pipeline"""

import numpy as np

# Define the missing variables based on previous API call
CLICKUP_API_TOKEN = "pk_93882701_5X39IECQRBNWFTVZBYSJH5CXKU79HS55" # Corrected API Token
BASE_URL = "https://api.clickup.com/api/v2/list/901202319556/task"
PARAMS = {"subtasks": "true"}

tasks = fetch_clickup_tasks(api_token=CLICKUP_API_TOKEN,base_url=BASE_URL,params=PARAMS,
)

print(f"Number of tasks fetched: {len(tasks)}")
if tasks:
    print(f"Tags of first task: {tasks[0].get('tags')}")
    # Let's inspect tags for all tasks
    all_tags = [t.get('tags') for t in tasks if t.get('tags')]
    print(f"All non-empty tags found: {all_tags}")

raw_df = normalize_tasks(tasks)
raw_df = apply_employment_status(raw_df, resigned_names)
raw_df = clean_text_columns(raw_df)

print(f"Tasks pulled: {len(raw_df):,}")
display(raw_df.head(3))

raw_df['Expire Date'] = epoch_ms_to_date(raw_df['Expire Date'])
raw_df['date_created'] = epoch_ms_to_datetime(raw_df['date_created'])
raw_df['Update Date'] = epoch_ms_to_datetime(raw_df['Update Date'])
raw_df['due_date'] = epoch_ms_to_date(raw_df['due_date'])

print("\nraw_df with converted date formats:")
display(raw_df.head())

raw_df["Certification Name"].unique()

raw_df["CU Status"].unique()

raw_df.rename(columns={'CU Status': 'Status'}, inplace=True)
display(raw_df.head())

import pandas as pd

certifications = [
    'SnowPro Advanced: Data Engineer',
    'Salesforce Certified Agentforce Specialist',
    'Salesforce Certified Mulesoft Developer 1',
    'Snowflake Sales Professional',
    'Snowflake Technical Sales Professional',
    'Alteryx Designer Advance',
    'Alteryx Designer Core',
    'SnowPro Core',
    'AWS Certified Solutions Architect - Associate',
    'AWS Data Engineer - Associate',
    'Salesforce',
    'Alteryx Server Administration',
    'Other',
    'Alteryx Designer Advanced',
    'Clickup Certification Board Changes',
    'AWS Cloud Practitioner',
    'Map out study path and resources',
    'Map out how long it should take to obtain cert',
    'Find out which certs and details',
    'Data Cloud',
    'Investigate learning paths/options',
    'PySpark',
    'Alteryx',
    'AWS',
    'Snowflake'
]



# -------------------------------
# 1. Technology grouping function
# -------------------------------
def classify_technology(cert):
    cert_lower = cert.lower()

    if 'snowpro' in cert_lower or 'snowflake' in cert_lower:
        return 'Snowflake'
    elif 'salesforce' in cert_lower or 'mulesoft' in cert_lower or 'agentforce' in cert_lower or 'data cloud' in cert_lower:
        return 'Salesforce'
    elif 'alteryx' in cert_lower:
        return 'Alteryx'
    elif 'aws' in cert_lower:
        return 'AWS'
    elif 'pyspark' in cert_lower:
        return 'PySpark'
    elif 'clickup' in cert_lower:
        return 'ClickUp'
    elif 'study path' in cert_lower or 'learning path' in cert_lower or 'find out which certs' in cert_lower:
        return 'Planning / Research'
    elif cert_lower == 'other':
        return 'Other'
    else:
        return 'Unclassified'

# -------------------------------
# 2. Hierarchy / level function
# -------------------------------
def classify_hierarchy(cert):
    cert_lower = cert.lower()

    if 'practitioner' in cert_lower:
        return 'Entry'
    elif 'core' in cert_lower:
        return 'Core'
    elif 'associate' in cert_lower:
        return 'Associate'
    elif 'developer 1' in cert_lower:
        return 'Associate'
    elif 'specialist' in cert_lower:
        return 'Specialist'
    elif 'advanced' in cert_lower or 'advance' in cert_lower:
        return 'Advanced'
    elif 'professional' in cert_lower:
        return 'Professional'
    elif 'administration' in cert_lower or 'administrator' in cert_lower:
        return 'Administrator'
    elif cert_lower in ['aws', 'snowflake', 'salesforce', 'alteryx', 'pyspark', 'data cloud']:
        return 'Technology Only'
    elif 'study path' in cert_lower or 'learning path' in cert_lower or 'find out which certs' in cert_lower:
        return 'Planning / Research'
    elif cert_lower == 'other':
        return 'Other'
    else:
        return 'Unspecified'

# Apply classification
raw_df['technology'] = raw_df['Certification Name'].apply(classify_technology)
raw_df['hierarchy'] = raw_df['Certification Name'].apply(classify_hierarchy)

# -------------------------------
# 3. Grouped output
# -------------------------------
grouped = raw_df.groupby(['technology', 'hierarchy'])['Certification Name'].apply(list).reset_index()

print(grouped)

raw_df['hierarchy']

import numpy as np
import pandas as pd

# Redefine the helper functions locally to fix the 'CU Status' KeyError.
# These definitions will override the ones from cell 33521efd for the current execution context.

def build_completed_branch(df: pd.DataFrame) -> pd.DataFrame:
    completed = df.copy()
    completed = completed[(completed["Name"].notna()) | (completed["due_date"].notna())]
    completed = completed[completed["Status"].eq("Done")] # Changed from "CU Status" to "Status"
    completed = completed[completed["Tag"].eq("cert")]

    completed["Record Date"] = completed["date_created"].dt.normalize()
    completed["Last Updated"] = completed["Update Date"].dt.normalize()
    completed["Expiration Date"] = np.where(
        completed["Expire Date"].isna(),
        (pd.Timestamp.today().normalize() + pd.DateOffset(years=10)),
        completed["Expire Date"]
    )
    completed["Expiration Date"] = pd.to_datetime(completed["Expiration Date"], errors='coerce').dt.normalize()
    completed["Status"] = np.where(
        pd.Timestamp.today().normalize() > completed["Expiration Date"],
        "Expired",
        "Active"
    )
    completed["Latest Flag"] = "1"

    max_record = (
        completed.groupby(["Name", "Certification Name"], dropna=False)["Record Date"]
        .max()
        .rename("Max_Record Date")
        .reset_index()
    )
    completed = completed.merge(max_record, on=["Name", "Certification Name"], how="left")
    completed["Latest Flag"] = np.where(
        completed["Record Date"].eq(completed["Max_Record Date"]),
        "1",
        "0"
    )
    completed = completed.drop(columns=["Max_Record Date"])

    keep_cols = [
        "Name", "Record Date", "Last Updated", "Latest Flag",
        "Certification Name", "Expiration Date", "Status", "Employment Status"
    ]
    return completed[keep_cols].copy()

def build_planned_branch(df: pd.DataFrame) -> pd.DataFrame:
    planned = df.copy()
    planned = planned[(planned["Name"].notna()) | (planned["due_date"].notna())]
    planned = planned[planned["Status"].ne("Done")] # Changed from "CU Status" to "Status"
    planned = planned[planned["Tag"].eq("cert")]

    planned["Planned Exam Date"] = planned["due_date"]
    planned["Record Date"] = planned["date_created"].dt.normalize()
    planned["Last Updated"] = planned["Update Date"].dt.normalize()
    planned["Status"] = "Planned"
    planned["Latest Flag"] = "1"

    keep_cols = [
        "Name", "Record Date", "Last Updated", "Latest Flag",
        "Certification Name", "Planned Exam Date", "Status", "Employment Status"
    ]
    return planned[keep_cols].copy()


completed_df = build_completed_branch(raw_df)
planned_df = build_planned_branch(raw_df)

base_cert_df = pd.concat([completed_df, planned_df], ignore_index=True, sort=False)
base_cert_df = standardise_certification_fields(base_cert_df)
base_cert_df = base_cert_df[base_cert_df["Certification Name"].notna() & (base_cert_df["Certification Name"].astype(str).str.strip() != "")]

display(base_cert_df.head())
print(base_cert_df.shape)

import datetime
import pandas as pd

# Assuming START_DATE and END_DATE are not defined, setting placeholders for demonstration
if 'START_DATE' not in locals() and 'START_DATE' not in globals():
    START_DATE = datetime.date(2023, 1, 1) # Example start date
if 'END_DATE' not in locals() and 'END_DATE' not in globals():
    END_DATE = datetime.date(2024, 12, 31) # Example end date

# Before calling prepare_glossary, ensure the 'glossary' DataFrame (which is df_flattened)
# has the columns expected by prepare_glossary and for the subsequent merge.

# Make a copy to avoid modifying the original df_flattened if it's used elsewhere
_glossary_for_preparation = glossary.copy()

# Rename 'name' column to 'Certification Name' as expected by subsequent functions
if 'name' in _glossary_for_preparation.columns and 'Certification Name' not in _glossary_for_preparation.columns:
    _glossary_for_preparation = _glossary_for_preparation.rename(columns={'name': 'Certification Name'})

# Add a placeholder 'Name' column to _glossary_for_preparation to prevent KeyError in standardise_certification_fields
if 'Name' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Name'] = ''

# Apply standardise_certification_fields to get 'Technology' and standardized 'Certification Name'
# This function is designed to work on the Certification Name and derive Technology.
_glossary_for_preparation = standardise_certification_fields(_glossary_for_preparation)

# Add placeholder columns if they are missing, as expected by prepare_glossary
# and ensure they have appropriate dtypes for the transformations within prepare_glossary
if 'Prerequisites' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Prerequisites'] = ''
if 'Cost' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Cost'] = '0' # Default to string '0' for processing by replace("$", "")
if 'Currency' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Currency'] = 'USD'
if 'Validity (Years)' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Validity (Years)'] = pd.NA # Use pandas NA for numeric type
if 'Partner' not in _glossary_for_preparation.columns:
    _glossary_for_preparation['Partner'] = 0 # Default to 0 for integer type

glossary_prepared = prepare_glossary(_glossary_for_preparation)


matched = base_cert_df.merge(
    glossary_prepared,
    on=["Technology", "Certification Name"],
    how="left"
)

date_spine = build_date_spine(START_DATE, END_DATE)
expanded = expand_by_date(matched, date_spine)

final_df = recompute_status_over_time(expanded)
final_df = finalise_output(final_df)

display(final_df.head())
print(final_df.shape)

today = pd.to_datetime(datetime.date.today())
final_df['is_valid'] = np.where(
    final_df['Expiration Date'] >= today,
    'yes',
    'no'
)

print("DataFrame with 'is_valid' column added:")
display(final_df.head())

print("Unique employee names:")
print(raw_df['Name'].unique())

import pandas as pd

# -----------------------------
# 0. Add 'hierarchy' column to final_df
# -----------------------------
# Ensure classify_hierarchy is available, if not, it should be in an earlier cell.
# Assuming classify_hierarchy is in the kernel.
final_df['hierarchy'] = final_df['Certification Name'].apply(classify_hierarchy)

# Create a temporary DataFrame with the required columns and correct names for processing
df_temp = pd.DataFrame()
df_temp['employee_name'] = final_df['Name']
df_temp['certification'] = final_df['Certification Name']
df_temp['obtained_date'] = pd.to_datetime(final_df['Record Date'], errors='coerce')
df_temp['technology'] = final_df['Technology']
df_temp['hierarchy'] = final_df['hierarchy'] # Use the newly added hierarchy column

# Defensive check for 'Expiration Date' before accessing
if 'Expiration Date' in final_df.columns:
    df_temp['current_expiration_date'] = final_df['Expiration Date'] # Keep a reference to the existing expiry
else:
    print("Warning: 'Expiration Date' not found in final_df. Assigning NaT to df_temp['current_expiration_date'].")
    df_temp['current_expiration_date'] = pd.NaT # Assign a default null date value

df_temp['Date'] = final_df['Date'] # Keep Date for final merge

# -----------------------------
# 1. Clean dates
# -----------------------------
# Base rule: expiry = obtained_date + 2 years
df_temp["expiry_date"] = df_temp["obtained_date"] + pd.DateOffset(years=2)

# -----------------------------
# 2. Define hierarchy ranking
# -----------------------------
hierarchy_rank = {
    "Technology Only": 0,
    "Entry": 1,
    "Core": 2,
    "Associate": 3,
    "Administrator": 4,
    "Specialist": 5,
    "Advanced": 6,
    "Professional": 7,
    "Other": -1,
    "Planning / Research": -1,
    "Unspecified": -1
}

df_temp["hierarchy_rank"] = df_temp["hierarchy"].map(hierarchy_rank).fillna(-1)

# -----------------------------
# 3. Find the latest highest cert per employee + technology
# -----------------------------
# Sort so that within each employee/technology:
# - highest hierarchy comes first
# - if same hierarchy, latest obtained_date comes first
df_sorted = df_temp.sort_values(
    by=["employee_name", "technology", "hierarchy_rank", "obtained_date"],
    ascending=[True, True, False, False]
)

# Pick the top certification per employee + technology
highest_cert = (
    df_sorted.groupby(["employee_name", "technology"], as_index=False)
    .first()[["employee_name", "technology", "expiry_date"]]
    .rename(columns={"expiry_date": "group_expiry_date"})
)

# -----------------------------
# 4. Update expiry dates
# -----------------------------
# Merge back the highest/latest expiry date for that technology
df_temp = df_temp.merge(highest_cert, on=["employee_name", "technology"], how="left")

# Final rule:
# use the higher certification expiry date for all certs in that technology
df_temp["expiry_date"] = df_temp["group_expiry_date"]

# Optional cleanup
df_temp.drop(columns=["group_expiry_date"], inplace=True)

print(df_temp[[
    "employee_name", "certification", "technology",
    "hierarchy", "obtained_date", "expiry_date"
]])

# Merge relevant updated columns back into the original final_df
# Use `Date`, `Name`, `Certification Name` from `final_df` as merge keys
# And `Date`, `employee_name`, `certification` from `df_temp`
# This ensures that we are correctly matching rows from the temporary processing DataFrame
# back to the original `final_df`.

# First, drop existing Expiration Date from final_df to avoid conflicts on update
if 'Expiration Date' in final_df.columns:
    final_df = final_df.drop(columns=['Expiration Date'])

# Select and rename columns from df_temp for merging to avoid conflicts
df_temp_to_merge = df_temp[['Date', 'employee_name', 'certification', 'hierarchy', 'expiry_date']].copy()
df_temp_to_merge.rename(columns={'hierarchy': 'hierarchy_temp', 'expiry_date': 'expiry_date_temp'}, inplace=True)

final_df = final_df.merge(
    df_temp_to_merge,
    left_on=['Date', 'Name', 'Certification Name'],
    right_on=['Date', 'employee_name', 'certification'],
    how='left'
    # suffixes argument removed as explicit renaming is used
)

# Update the hierarchy and Expiration Date in final_df
final_df['hierarchy'] = final_df['hierarchy_temp']
final_df['Expiration Date'] = final_df['expiry_date_temp']

# Clean up the temporary columns created by the merge
final_df.drop(columns=['employee_name', 'certification', 'hierarchy_temp', 'expiry_date_temp'], inplace=True)

final_df

final_df["Status"].unique()

final_df['Status'] = final_df['Status'].replace('Projected Expired', 'Active')
display(final_df.head())
print(final_df['Status'].unique())

final_df = final_df[final_df['Status'] != 'Planned - No Exam Date']
print("Unique statuses after filtering:")
print(final_df['Status'].unique())



import datetime

today = pd.to_datetime(datetime.date.today())
final_df['Validity (Years)'] = (final_df['Expiration Date'] - today).dt.days / 365.25

print("DataFrame with 'Years Remaining' column added:")
display(final_df.head())

cleaned_df = final_df[['Name', 'Certification Name', 'Status','Technology', 'Record Date', 'Expiration Date','Employment Status']]
display(cleaned_df.head())

print(final_df['Status'].unique())

cleaned_df = final_df.drop_duplicates(subset=['Name', 'Technology'])
print("DataFrame after removing duplicates:")
display(cleaned_df)

cleaned_df.info()

desired_df = cleaned_df[['Name', 'Certification Name', 'Technology', 'Status', 'Employment Status', 'Expiration Date', 'Record Date']]
display(desired_df.head())

desired_df .to_csv('certifications.csv', index=False)
print("DataFrame exported to 'cleaned_certifications.csv' successfully.")

