# -*- coding: utf-8 -*-
"""schedule_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m61Y_QehnxkDIRoOmrCdZtNSoD0vYyz8
"""

df = pd.read_csv('output (2).csv', delimiter='`')
df

def extract_names_from_email(email):
    if pd.isna(email): # Handle NaN values
        return None, None

    local_part = email.split('@')[0]
    parts = local_part.replace('.', ' ').split(' ')

    first_name = parts[0].capitalize() if parts else None
    surname = parts[1].capitalize() if len(parts) > 1 else None

    return first_name, surname

df['extracted_first_name'], df['extracted_surname'] = zip(*df['user_email'].apply(extract_names_from_email))

print("Extracted first names and surnames. Here are the first few rows with the new columns:")
print(df[['user_email', 'extracted_first_name', 'extracted_surname']].head())

# Update extracted_surname for Andrew Milner
df.loc[df['extracted_first_name'] == 'Andrew', 'extracted_surname'] = 'Milner'

if 'Mark' in df['extracted_first_name'].unique():
    df.loc[df['extracted_first_name'] == 'Mark', 'extracted_surname'] = 'Gelman'
else:
    print("Note: No entries found for 'Mark' in 'extracted_first_name'. Surname 'Gelman' not applied for any rows.")

print("Updated surnames. Here are the first few rows with the new columns:")
print(df[['user_email', 'extracted_first_name', 'extracted_surname']].head())

print("Missing values per column:")
print(df.isnull().sum())

print("\nPercentage of missing values per column:")
print(df.isnull().sum() / len(df) * 100)

# Impute missing values in 'meeting_subject' with 'No Meeting Subject'
df['meeting_subject'].fillna('No Meeting Subject', inplace=True)

print("Missing values in 'meeting_subject' after imputation:")
print(df['meeting_subject'].isnull().sum())

print("\nFirst 5 rows of 'meeting_subject' column after imputation:")
print(df['meeting_subject'].head())

print("\nLast 5 rows of 'meeting_subject' column after imputation (to show any imputed values):")
print(df['meeting_subject'].tail())