GRANT USAGE ON DATABASE SCHEDULE_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA SCHEDULE_DB.PUBLIC TO ROLE ACCOUNTADMIN;
USE ROLE ACCOUNTADMIN;

-- Grant the Cortex User role to your current role
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN; 
-- (Or replace SYSADMIN with the role you are currently using)

-- Ensure you have access to the Database and Schema where the data lives
GRANT USAGE ON DATABASE SCHEDULE_DB TO ROLE ACCOUNTADMIN;
GRANT USAGE ON SCHEMA SCHEDULE_DB.PUBLIC TO ROLE ACCOUNTADMIN;

USE DATABASE SCHEDULE_DB;
USE SCHEMA PUBLIC;

LIST @MY_AI_MODELS;
