CREATE DATABASE IF NOT EXISTS SCHEDULE_DB;
CREATE SCHEMA IF NOT EXISTS SCHEDULE_DB.PUBLIC;

CREATE OR REPLACE TABLE SCHEDULE_DB.PUBLIC.EMPLOYEE_SCHEDULE (
    USER_EMAIL STRING,
    FIRST_NAME STRING,
    SCHEDULE_DATE DATE,
    MEETING_SUBJECT STRING,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    LOAD_PERCENTAGE FLOAT,
    DURATION_MINUTES FLOAT,
    WEEKDAY STRING,
    MONTH_NAME STRING,
    TIME_OF_DAY STRING,
    LOAD_BAND STRING,
    SUMMARY_SENTENCE STRING
);