name: Run Python Pipeline

on:
  schedule:
    - cron: '*/9 * * * *' #https://crontab.guru/ 
  workflow_dispatch:

env:
    FILE_NAME: "Schedule/Three_Month_Team_Schedule.xlsx"

jobs:
    pipeline:
        runs-on: ubuntu-latest
              
        steps:
        
            - name: Checkout repo
              uses: actions/checkout@v6 # Allows the GitHub runner access to the repo content
                  
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: "3.11.0"

            - name: Setup dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r Schedule/requirements.txt
            
            - name: Extract Outlook data
              env:
                CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
                CLICKUP_SPACE_IDS: ${{ secrets.CLICKUP_SPACE_IDS }}
                CLICKUP_ASSIGNEES: ${{ secrets.CLICKUP_ASSIGNEES }}
                OUTLOOK_USER_EMAIL: ${{ secrets.OUTLOOK_USER_EMAIL }}
                TENANT_ID: ${{ secrets.TENANT_ID }}
                CLIENT_ID: ${{ secrets.CLIENT_ID }}
                CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

              run: python Schedule/current_month.py
              
            # - name: Remove old file 
            #   uses: EndBug/add-and-commit@v9
            #   with:
            #       remove: ${{ env.FILE_NAME }}
            #       committer_name: "GitHub Actions"
            #       message: "removing old schedule"

            # - name: Set current_timestamp
            #   run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

            # - name: Upload artifact
            #   uses: actions/upload-artifact@v4
            #   with:
            #       path: ${{ env.FILE_NAME }}
              
            - name: Add new file 
              if: ${{ success() }}
              uses: EndBug/add-and-commit@v9
              with:
                  add: "${{ env.FILE_NAME }}"
                  committer_name: "GitHub Actions"
                  message: "Added new schedule at ${{ env.NOW }}"

            # - name: Transform and load to Snowflake
            #   env:
            #     SNOWFLAKE_ACCOUNT:  ${{ secrets.SNOWFLAKE_ACCOUNT }}
            #     SNOWFLAKE_USER:     ${{ secrets.SNOWFLAKE_USER }}
            #     SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            #     SNOWFLAKE_WAREHOUSE: COMPUTE_WH
            #   run: python pipeline_transform_load.py 
            # - name: Install dependencies
            #   run: |
            #     pip install pandas numpy snowflake-connector-python
