name: 3 Month Report Flow

on:
  schedule:
    - cron: '0 */4 * * *' #https://crontab.guru/
  workflow_dispatch:

env:
    FILE_NAME: "./Schedule/Aggregated_Hours.xlsx"

jobs:
    extract_report_date:
        runs-on: ubuntu-latest

        outputs:
            base_report: ${{ steps.storage.outputs.base_report }}
              
        steps:
        
            - name: Checkout repo
              uses: actions/checkout@v6 # Allows the GitHub runner access to the repo content
                  
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: "3.11.0"

            - name: Setup dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r Schedule/requirements.txt
                
            # - name: Extract 3 Month data
            #   run: python Schedule/3_month_excel.py

            - name: Store output
              id: storage
              run: |
                  
                  echo "base_report=python Schedule/3_month_excel.py" >> $GITHUB_OUTPUT
# python Schedule/3_month_excel.py
    print_job:
        runs-on: ubuntu-latest
        needs: extract_report_date
        steps:
          - run: echo ${{needs.extract_report_date.outputs.base_report}}
      
#
#            - name: Aggregate Hours + Generate Report
#              run: python Schedule/agg_hours.py
#
#            - name: Set current_timestamp
#              run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
#              
#            - name: Commit new file 
#              uses: EndBug/add-and-commit@v9
#              with:
#                  add: "${{ env.FILE_NAME }}"
#                  committer_name: "GitHub Actions"
#                  message: "Added new Outlook data at ${{ env.NOW }}"
#


#            - name: Email report
#              uses: dawidd6/action-send-mail@<REF>
#              with:
#                  connection_url: ${{secrets.MAIL_CONNECTION}}
#                  server_address: smtp-mail.outlook.com
#                  server_port: 587
#                  secure: true
#                  username: ${{secrets.MAIL_USERNAME}}
#                  password: ${{secrets.MAIL_PASSWORD}}
#                  subject: Github Actions job result
#                  to: tcalana2013@gmail.com
#                  from: "Thando Calana <thando.calana@slipstreamdata.co.za>"
#                  attachments: "${{ env.FILE_NAME }}"
