name: 3 Month Report Flow

on:
  schedule:
    - cron: '0 */4 * * *' #https://crontab.guru/
  workflow_dispatch:

env:
    FILE_NAME: "./Schedule/Aggregated_Hours.xlsx"  
    CLICKUP_TOKEN: ${{ secrets.CLICKUP_TOKEN }}
    CLICKUP_SPACE_IDS: ${{ secrets.CLICKUP_SPACE_IDS }}
    CLICKUP_ASSIGNEES: ${{ secrets.CLICKUP_ASSIGNEES }}
    OUTLOOK_USER_EMAIL: ${{ secrets.OUTLOOK_USER_EMAIL }}
    TENANT_ID: ${{ secrets.TENANT_ID }}
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
    extract_report_date:
        runs-on: ubuntu-latest

        outputs:
            base_report: ${{ steps.storage.outputs.base_report }}
              
        steps:
        
            - name: Checkout repo
              uses: actions/checkout@v6 # Allows the GitHub runner access to the repo content
                  
            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: "3.11.0"

            - name: Setup dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r Schedule/requirements.txt
                
            - name: Extract report data
              run: python Schedule/extract_report_csv.py

            - name: Aggregate Hours + Generate Report
              run: python Schedule/agg_hours.py
#
#            - name: Set current_timestamp
#              run: echo "NOW=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
#              
#            - name: Commit new file 
#              uses: EndBug/add-and-commit@v9
#              with:
#                  add: "${{ env.FILE_NAME }}"
#                  committer_name: "GitHub Actions"
#                  message: "Added new Outlook data at ${{ env.NOW }}"
#


#            - name: Email report
#              uses: dawidd6/action-send-mail@<REF>
#              with:
#                  connection_url: ${{secrets.MAIL_CONNECTION}}
#                  server_address: smtp-mail.outlook.com
#                  server_port: 587
#                  secure: true
#                  username: ${{secrets.MAIL_USERNAME}}
#                  password: ${{secrets.MAIL_PASSWORD}}
#                  subject: Github Actions job result
#                  to: tcalana2013@gmail.com
#                  from: "Thando Calana <thando.calana@slipstreamdata.co.za>"
#                  attachments: "${{ env.FILE_NAME }}"
